UMC-GetIT/GetIT-server

src/main/java/com/example/getIt/entity/ComputerSubEntity.java, src/main/java/com/example/getIt/entity/PhoneSubEntity.java, src/main/java/com/example/getIt/entity/ProductEntity.java, src/main/java/com/example/getIt/entity/WebsiteEntity.java
=> Feat: Create ProductEntity(include Sub)&WebsiteEntity

src/main/java/com/example/getIt/controller/UserController.java, src/main/java/com/example/getIt/repository/UserRepository.java, src/main/java/com/example/getIt/service/UserService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java, src/main/java/com/example/getIt/util/ValidationRegex.java
=> Feat: Create User sign api

build.gradle, src/main/java/com/example/getIt/DTO/UserDTO.java, src/main/java/com/example/getIt/controller/UserController.java, src/main/java/com/example/getIt/entity/ProductEntity.java, src/main/java/com/example/getIt/service/UserService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java, src/main/java/com/example/getIt/util/JwtService.java, src/main/java/com/example/getIt/util/SHA256.java, src/main/java/com/example/getIt/util/Secret.java
[Feat: Add password encryption, jwt]
=> Feat: Add password encryption, jwt

src/main/java/com/example/getIt/DTO/UserDTO.java, src/main/java/com/example/getIt/controller/UserController.java, src/main/java/com/example/getIt/entity/UserProductEntity.java, src/main/java/com/example/getIt/repository/UserRepository.java, src/main/java/com/example/getIt/service/UserService.java
유저 정보 불러오기 기능 추가했습니다.
그런데 post 정보를 같이 불러오는 것에 실패하여 유저 정보 불러온 것만 PR하였습니다.
=> Feat: getUser기능 추가

src/main/java/com/example/getIt/DTO/UserDTO.java, src/main/java/com/example/getIt/controller/UserController.java, src/main/java/com/example/getIt/entity/UserEntity.java, src/main/java/com/example/getIt/service/UserService.java
=> Fix: sign-in change

build.gradle
=> Fix: test fixed

src/main/java/com/example/getIt/controller/UserController.java, src/main/java/com/example/getIt/service/UserService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java, src/test/java/com/example/getIt/GetItApplicationTests.java
=> Feat: Login

src/main/java/com/example/getIt/DTO/ProductDTO.java, src/main/java/com/example/getIt/DTO/WebsiteDTO.java, src/main/java/com/example/getIt/controller/ProductController.java, src/main/java/com/example/getIt/entity/WebsiteEntity.java, src/main/java/com/example/getIt/repository/WebsiteRepository.java, src/main/java/com/example/getIt/service/ProductService.java
=> Feat: getProduct

src/main/java/com/example/getIt/DTO/UserDTO.java, src/main/java/com/example/getIt/repository/UserProductRepository.java, src/main/java/com/example/getIt/service/UserService.java
=> Fix: userInfo

build.gradle, src/main/java/com/example/getIt/config/SecurityConfig.java, src/main/java/com/example/getIt/user/DTO/SessionUser.java, src/main/java/com/example/getIt/user/controller/UserController.java, src/main/java/com/example/getIt/user/entity/UserEntity.java, src/main/java/com/example/getIt/user/jwt/DTO/OAuthAttributes.java, src/main/java/com/example/getIt/user/jwt/OAuth2SuccessHandler.java, src/main/java/com/example/getIt/user/jwt/service/CustomOAuth2UserService.java, src/main/java/com/example/getIt/user/service/UserService.java, src/main/java/com/example/getIt/util/BaseEntity.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java
https://velog.io/@swchoi0329/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0%EC%99%80-OAuth-2.0%EC%9C%BC%EB%A1%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84#%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%EC%84%A4%EC%A0%95-%EB%93%B1%EB%A1%9D
위 블로그 참고
=> FEAT: create google login api oauth 2.0

build.gradle, src/main/java/com/example/getIt/product/DTO/ItemDTO.java, src/main/java/com/example/getIt/product/controller/SearchController.java, src/main/java/com/example/getIt/util/NaverShopSearch.java, src/main/resources/application.properties
=> FEAT: search api

src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/service/ProductService.java
=> Feat: all products API

src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/entity/ProductEntity.java, src/main/java/com/example/getIt/product/entity/ReviewEntity.java, src/main/java/com/example/getIt/product/repository/ProductRepository.java, src/main/java/com/example/getIt/product/repository/ReviewRepository.java, src/main/java/com/example/getIt/product/service/ProductService.java, src/main/java/com/example/getIt/user/service/UserService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java
review api를 임시로 작성했습니다. 아직 상품 세부 정보 조회가 작성되지 않아, 세부 정보를 frontend 에서 server로 전달할 때 전달 하는 방법에 따라 review api 세부 내용을 바꿔야 할 것 같습니다.!
=> FEAT: create review api

build.gradle, src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/service/ProductService.java, src/main/java/com/example/getIt/util/NaverShopSearch.java
상세 제품 조회에서 크롤링한 부분들을 리스트에 저장해서 contains 함수를 사용해 카테고리별로 원하는 값만 출력할 수 있도록 했습니다! 제품마다 정보 내용이 거의 비슷하긴 하지만 순서가 다른 경우도 간간히 있어서 비교하기 api 제작할 때 다시 수정해야할 것 같습니다. 추가로 서버로 정보 불러오도록 코드 차후에 수정하도록 하겠습니다!
=> FEAT: detail product api

src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/entity/ProductEntity.java, src/main/java/com/example/getIt/product/service/ProductService.java, src/main/java/com/example/getIt/user/DTO/UserDTO.java, src/main/java/com/example/getIt/user/controller/UserController.java, src/main/java/com/example/getIt/user/service/UserService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java
좋아요 등록 api와 좋아요 목록 조회 api 생성하였습니다.
좋아요 취소 api는 추후 추가하겠습니다.
=> FEAT : likeAPI

src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/service/ProductService.java
=> Refactor: detail product api

src/main/java/com/example/getIt/product/entity/ReviewEntity.java, src/main/java/com/example/getIt/product/repository/ReviewRepository.java, src/main/java/com/example/getIt/user/DTO/UserDTO.java, src/main/java/com/example/getIt/user/controller/UserController.java, src/main/java/com/example/getIt/user/entity/UserEntity.java, src/main/java/com/example/getIt/user/service/UserService.java
=> FEAT: reissue, create mypage

src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/service/ProductService.java
=> FEAT: product compare api

src/main/java/com/example/getIt/config/Signatures.java, src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/service/ProductService.java
네이버 검색 광고 api를 사용하여 최다로 검색한 추천 검색어 10개를 보여주는 api를 생성했습니다.
=> FEAT: recommend search words

src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/DTO/SpecDTO.java, src/main/java/com/example/getIt/product/controller/MainViewController.java, src/main/java/com/example/getIt/product/entity/ProductEntity.java, src/main/java/com/example/getIt/product/service/ProductService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java, src/main/java/com/example/getIt/util/NaverSearchAPI.java, src/main/java/com/example/getIt/util/NaverShopSearch.java
=> FEAT: Find specification api 

src/main/java/com/example/getIt/product/controller/ProductController.java, src/main/java/com/example/getIt/product/repository/UserProductRepository.java, src/main/java/com/example/getIt/product/service/ProductService.java
=> FIX: LikeAPI

src/main/java/com/example/getIt/jwt/exception/JwtAccessDeniedHandler.java
많은 pr 및 merge 죄송합니다ㅜㅜㅜㅜㅜㅜㅜ 실수로 바꾸지 않은 코드가 너무 많았어요,,ㅜㅜㅜㅜㅜㅜㅜㅜㅜ
=> FIX : CHANGE JWT TOKEN RESPONSE (401, 403 ERROR) SEQUENCE 2

src/main/java/com/example/getIt/product/DTO/SpecDTO.java, src/main/java/com/example/getIt/product/controller/MainViewController.java, src/main/java/com/example/getIt/product/entity/SpecEntity.java, src/main/java/com/example/getIt/product/repository/SpecRepository.java, src/main/java/com/example/getIt/product/service/ProductService.java
추천 사양 api 수정했습니다. /main/findspec 경로로 들어가는 경우 콘솔에 DB 입출력 변화가 떠서 이 부분에 대해서 코드를 더 함 봐줘야할 거 같아요..!
=> FEAT: Find specification api

build.gradle, src/main/java/com/example/getIt/config/RedisRepositoryConfig.java, src/main/java/com/example/getIt/config/SecurityConfig.java, src/main/java/com/example/getIt/jwt/JwtFilter.java, src/main/java/com/example/getIt/jwt/OAuth2SuccessHandler.java, src/main/java/com/example/getIt/jwt/TokenProvider.java, src/main/java/com/example/getIt/jwt/config/JwtSecurityConfig.java, src/main/java/com/example/getIt/jwt/entity/RefreshTokenEntity.java, src/main/java/com/example/getIt/user/controller/UserController.java, src/main/java/com/example/getIt/user/service/UserService.java
redis를 사용하여 로그아웃을 하게 되면 현재 남아있는 accesstoken의 시간을 만료했으며, oauth2로 로그인(google, naver) 한 user도 로그아웃 가능하도록 했습니다. (로그아웃/ 소셜 로그아웃 합침) redis를 사용하기 위해서는 redis window 용으로 설치하여 port를 활성화해야 합니다.
=> FEAT: LOGOUT API

src/main/java/com/example/getIt/jwt/service/CustomOAuth2UserService.java, src/main/java/com/example/getIt/user/entity/UserEntity.java
소셜 로그인 시, 프로필 사진과 이름이 자동으로 변경되는 기능을 없앴음.
=> FIX: do not update oauth2 user's profile

src/main/java/com/example/getIt/product/service/ProductService.java
=> FIX: change naver css class name

src/main/java/com/example/getIt/product/DTO/ItemDTO.java, src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/service/ProductService.java
=> FIX: find product & search api

src/main/java/com/example/getIt/product/DTO/ProductDTO.java, src/main/java/com/example/getIt/product/service/ProductService.java
메인 추천, 상품 카테고리 Response 수정하였습니다.
=> FIX: CategoryAPI ResponseBody

src/main/java/com/example/getIt/product/service/ProductService.java, src/main/java/com/example/getIt/util/BaseResponseStatus.java
리뷰 리스트 조회 위해 baseresponse값 추가, 크롤링 url 조건 추가했습니다
=> FIX: review product detail api
